#mysql数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dylan?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456xxf
    driver-class-name: com.mysql.cj.jdbc.Driver #
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10
      read-only: false
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**
  resources:
    add-mappings: false
  static-locations:
    - classpath:resources
    - classpath:static

logging:
  level:
    com.du.dylan: debug
  file:
    path: log
  max-history: 30


