# Master datasource config
application:
  server:
    db:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/dylan?allowPublicKeyRetrieval=true&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        port: 3306
        username: root
        password: 123456xxf

